### ISSUE TITLE
Modular definition of schemas (extensibility)

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/apollo-server#100]
Hi, I'm actively working with apollo and loving the experience. I just want to contribute with an opinion on a possible improvement of schema handling. What I feel that is a drawback of the current approach is the monolithic definion of Apollo schema, which does not provide extensibility through packages. It is quite difficult to produce modules or import packages that add on top of current functionality (this authentication packages, different modules in economic systems and more).

What would be great is to have the possibility to define functionality per domain element, where each domain element would export the list of:

```
schema
resolvers
queries
queryResolvers
mutations
mutationResolvers
```

With a current approach it is possible to define only schema and resolvers and import it into Apollo, queries and mutations got left behind. I got this working in my apollo-mantra project but it's a rather silly solution which heavily depends on my custom functionality and makes no sense to share it. Would you consider implementing something like this in core?

**Comment by helfer** [comment]
Hey @tomitrescak, thanks for your feedback. Since we split out the schema generation to graphql-tools, I think it would be more appropriate to open this issue there, so I will close it here.
