### ISSUE TITLE
Component mounting before query returns

### ISSUE THREAD

**Issue by jktunney** [apollostack/apollo-server#105]
Hello,

I thought the data container was supposed to return before it allowed the new component to mount anything. Do I have to handle the fetch's "loading" state? It's very strange and I feel like there must be a simple solution. When i swap this
```
class GridContainer extends React.Component {

	render() {
		console.log("props")
		console.log(this.props)
		const workouts = this.props.data.workouts;
		
		return (
			<GridComponent workouts={workouts} />
		)
	}
};
```

for this: 

```
class GridContainer extends React.Component {
	constructor(props) {
		super(props)
	}
	render() {
		console.log("props")
		console.log(this.props)
		const workouts = this.props.data.workouts;
		console.log("workouts")
		console.log(workouts)
		
		return (
			<div>
				hello world
			</div>
		)
	}
};
```

i get:

![screen shot 2016-08-22 at 11 41 21 am](https://cloud.githubusercontent.com/assets/12723555/17861157/f3290724-685d-11e6-82d9-f767b1c7ebc1.png)

my data is there in the workouts array. but when i try to pass "workouts" to my GridComponent component, like this: 
```
class GridContainer extends React.Component {

	render() {
		console.log("props")
		console.log(this.props)
		const workouts = this.props.data.workouts;
		
		return (
			<GridComponent workouts={workouts} />
		)
	}
};
```
I get: 
![screen shot 2016-08-22 at 11 56 05 am](https://cloud.githubusercontent.com/assets/12723555/17861537/72a2219c-685f-11e6-9b85-b035d5adf44c.png)

It seems like the component wants to mount before the data is actually available to it, causing an error.   Any input would be much appreciated.

**Comment by stubailo** [comment]
Yes, you need to handle loading state yourself. The container doesn't have built-in logic to do anything special, other than pass through loading/error state to the child.

This is a pretty standard thing - handing loading state is very application-specific, and you usually don't want to block rendering a big part of your tree on a long server request.

**Comment by stubailo** [comment]
By the way - this might be better opened on apollo-client rather than the server.

**Comment by jktunney** [comment]
@stubailo thanks for clearing this up!
