### ISSUE TITLE
Transport batching seems to break on null/undefined values

### ISSUE THREAD

**Issue by Poincare** [apollostack/apollo-server#106]
There seems to be an issue with transport batching when one of the resolvers returns a `null` or `undefined` value. 

This issue can be reproduced by checking out the code [here](https://github.com/apollostack/GitHunt/pull/79) and `npm link`ing against [this PR](https://github.com/apollostack/apollo-client/pull/531) on Apollo Client.

## How to get `npm link` to work

After `npm link apollo-client` and running `GitHunt`, you will notice that there are two places within `react-apollo` that two internal imports are made: `apollo-client/errors` and `apollo-client/queries/getFromAST`. Change these to `apollo-client/lib/src/errors` and `apollo-client/lib/src/queries/getFromAST` and GitHunt should then work.

**Comment by helfer** [comment]
I think this might actually be a bug in the non-batching queries. `allowUndefinedInResolve` had a typo in it on the server, which means any time the user wasn't logged in, that resolver should have errored and sent back an error. That error was either not delivered on the server (unlikely), or it wasn't delivered on the client. We should look into this.

**Comment by helfer** [comment]
@Poincare did you ever figure out if this is a bug in apollo client?
