### ISSUE TITLE
How to suppress "Resolve function for "xyz" returned undefined"

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/apollo-server#107]
Is it possible? I don't care if that field is undefined.

Documentation says that I can enforce this behaviour with "forbidUndefinedInResolve", but I want opposite of that.

http://docs.apollostack.com/apollo-server/errors.html

**Comment by tomitrescak** [comment]
I even set { allowUndefinedInResolve: true } in graphql options and no luck.

**Comment by helfer** [comment]
For 0.2.0 you have to pass the option to `makeExecutableSchema`, which is a function from `graphql-tools`.

**Comment by tomitrescak** [comment]
Thanks for your answer!

Is there any documentation to graphql-tools? The documentation from Github points to old version of Apollo Server.

**Comment by helfer** [comment]
Right here: http://docs.apollostack.com/graphql-tools/generate-schema.html

**Comment by payner35** [comment]
Here is what I got so far...  https://github.com/payner35/reduxToast

But I'm still getting undefined errors


```
const executableSchema = makeExecutableSchema({
    typeDefs: Schema,
    resolvers: Resolvers,
    //connectors: Connectors,
});


createApolloServer({
    graphiql: true,
    pretty: true,
    schema: executableSchema,
    printErrors: true, // optional
    allowUndefinedInResolve: true // optional
});

```

**Comment by helfer** [comment]
@payner35 I'm pretty sure you have to pass that option to `makeExecutableSchema`, not into createApolloServer (which I assume is from meteor-integration).

**Comment by payner35** [comment]
Thanks @helfer .. working now

**Comment by mnpenner** [comment]
@helfer I think the [documentation](http://dev.apollodata.com/tools/graphql-tools/errors.html#forbidUndefinedInResolve) is out of date. It still says `forbidUndefinedInResolve` is a function and you should use it to update your schema like so:

```js
import { forbidUndefinedInResolve } from 'graphql-tools';

forbidUndefinedInResolve(schema); // TypeError: forbidUndefinedInResolve is not a function
```

Regardless, I can't get any errors to show. I'm trying

```js
module.exports = makeExecutableSchema({
    typeDefs: schema,
    resolvers: require('./resolvers'),
    allowUndefinedInResolve: false,
    printErrors: true,
    logger: {
        log: err => {
            console.log(err);
        }
    },
});
```

And when I run I query I get back:

```json
{"errors":[{"message":"Unknown operation named \"undefined\"."}]}
```

But no error is logged either to my terminal nor GraphiQL so I don't know what the issue is.
