### ISSUE TITLE
Moved to apollo-server from graphql-express and now I cant query anything via graphiql [SOLVED]

### ISSUE THREAD

**Issue by kesemdavid** [apollostack/apollo-server#114]
Title says it all.
Looks like it doesn't recognize my schema, since graphiql's Documentation tab keeps on loading and there's no auto-complete for the query.

When i used `graphql-express` everything worked fine.

This is how i set up my new ApolloExpress:

![apolloserver](https://cloud.githubusercontent.com/assets/21152044/18050257/2a4815b8-6df6-11e6-9583-bcb0fc26fda4.png)

**Comment by kesemdavid** [comment]
Did not notice my graphiql endpoint was set to 'graphiql' and not 'graphql'

**Comment by linonetwo** [comment]
Thanks for the pic... I don't even know how to set up graphiQL with so little docs.

**Comment by kesemdavid** [comment]
glad it helped somebody :)
