### ISSUE TITLE
Graphql-Relay with the Schema Language

### ISSUE THREAD

**Issue by fenos** [apollostack/apollo-server#122]
Hi, I'm willing to use **apollo-server/graphql-tools** which looks great to me 👍. 
But i don't want to use `apollo-client`, somehow i like much more Relay in a `React` context.

Anyway, Is there a way to use [graphql-relay-js](https://github.com/graphql/graphql-relay-js) package with the **nice** and **simple** Schema language that **graphql-tools** provide?

Thanks, for any hints

**Comment by stubailo** [comment]
Honestly part of the reason I like Apollo client is that it doesn't require a lot of very non-simple additions to the schema to work.

You could definitely write out all of the connection types and input types yourself, but I don't know if there is an easy way around that while also keeping the property that you can read your schema from the nice declarative format.

**Comment by fenos** [comment]
@stubailo Ok got it :) i'll give a try to `apollo-client`. After reading the doc I have few questions, where is the best place to ask? 👍

**Comment by stubailo** [comment]
Probably on the slack channel!

**Comment by tonyxiao** [comment]
Quick follow up here, could apollo server provide some nice tools to simplify the creation of a relay compliant graphQL server? Also does Apollo client make use of any of the relay compliant features of the GraphQL server if they exist?

**Comment by stubailo** [comment]
Apollo client doesn't use these features currently, since we feel they aren't necessarily appropriate for all backends, and we wanted to build something that anyone could use with any server.

Apollo server doesn't deal with schema creation - that would probably be something in GraphQL-tools. If you have any ideas you could open an issue there!
