### ISSUE TITLE
How to pass multiple items to field with iterable?

### ISSUE THREAD

**Issue by linonetwo** [apollostack/apollo-server#128]
![_20160909093424](https://cloud.githubusercontent.com/assets/3746270/18372738/60ca790e-7671-11e6-8c36-fed66147afeb.png)
![_20160909093637](https://cloud.githubusercontent.com/assets/3746270/18372740/61894fa0-7671-11e6-8288-98d3a645133d.png)

**Comment by linonetwo** [comment]
OK, found it.

I need to pass token to DistrictType, but when I pass 
```javascript
    children({ token, powerEntity }, { areaType, id }, context) {
      console.log(powerEntity.children);
      return { token, powerEntity: powerEntity.children };
    },
```
It warn about `"User Error: expected iterable, but did not find one for field PowerEntityType.children."`

So I just pass `return powerEntity.children ;` and foooooooooget to change DistrictType's field to receive it.

**Comment by helfer** [comment]
Since each of the items in a list runs its own resolver, you would have to pass the token to each of them separately, e.g. something like: `return powerEntity.children.map( item => Object.assign(item, { token }))` assuming that item is an object.

**Comment by linonetwo** [comment]
Thank you, that solved my problem.

![_20160909143912](https://cloud.githubusercontent.com/assets/3746270/18377759/808701de-769b-11e6-804d-d1a200e4d2c3.png)
