### ISSUE TITLE
Documentation for __resolveType

### ISSUE THREAD

**Issue by rdrey** [apollostack/apollo-server#13]
I had to read unit tests to figure out how to use `__resolveType`. 😅

**Comment by helfer** [comment]
It's actually in the docs, but I guess it's not easy to find: http://docs.apollostack.com/apollo-server/resolvers.html#addResolveFunctionsToSchema

Maybe we could break it out into a separate subsection under 'addingResolvers'. It could be called 'Interfaces & Unions'. Care to make a PR? :grin:

**Comment by rdrey** [comment]
Ah thanks, I might 😝  

I would like to split docs a little differently. At the moment the [Apollo Server](http://docs.apollostack.com/apollo-server/tools.html) page looks like the only page I really need as an `apollo-server` user and the other pages ([GraphQL type language](http://docs.apollostack.com/apollo-server/generate-schema.html), [Adding resolvers](http://docs.apollostack.com/apollo-server/resolvers.html), [Mocking](http://docs.apollostack.com/apollo-server/mocking.html), ...) look like they just document internal/utility functions.

If they had more generic page titles like "Schema, Resolvers, Mocks, Connectors", we could explain a little more about each parameter (with links to these pages from the Apollo Server parameters), followed by a section with `graphql-tools` internal functions that are clearly useful for people using these components separately.

**Comment by helfer** [comment]
Yeah, I agree. What you proposed sounds great to me. If you want, you can go ahead and start renaming them, and make a PR against the `server-refactor` branch which I've just created as a branch we can work on to make this happen!

**Comment by helfer** [comment]
Closing this here, we can track it in the docs repo.
