### ISSUE TITLE
Any support for https with apollo-client?

### ISSUE THREAD

**Issue by linonetwo** [apollostack/apollo-server#135]
I'm using graphQL for auth, can I use https between apollo-server and apollo-client?

**Comment by stubailo** [comment]
Yes! Is anything stopping you?

**Comment by linonetwo** [comment]
Thanks, that's great, I was just not very sure about it since I can't search out anything about graphQL and SSL work together.

After I finish my post about wrapping REST with apollo, I will write a post about using SSL with graphQL.

**Comment by stubailo** [comment]
Yeah I don't think there is anything special about it since both rest and GraphQL are just HTTP.
