### ISSUE TITLE
Error in Hapi example

### ISSUE THREAD

**Issue by siegesmund** [apollostack/apollo-server#141]
The example suggests importing ApolloHAPI as ``` import { ApolloHapi } from 'apollo-server';```

 The instructions should read ``` import { ApolloHAPI } from 'apollo-server';``` as ApolloHAPI is actually the name of the exported object.

**Comment by helfer** [comment]
@siegesmund Thanks! Can you make a quick PR to fix it please? You can edit the README.md directly on github.

**Comment by siegesmund** [comment]
Looking at the source in the Github repo, it looks like it was changed to camel case 5 days ago. The version on NPM reflects the old nomenclature. With the next version bump, the instructions will be correct. So, I guess, nevermind.

**Comment by helfer** [comment]
The docs / readme should be consistent with the currently released version though, so I still think this is an issue.

**Comment by siegesmund** [comment]
I agree. Wasn't sure when you were planning on releasing the next version. I'll make the pull request.

**Comment by siegesmund** [comment]
Corrections made in apollostack/apollo-server#142

**Comment by helfer** [comment]
Thanks for the PR, I just merged it!
