### ISSUE TITLE
Support for 64 bit int

### ISSUE THREAD

**Issue by tonyxiao** [apollostack/apollo-server#145]
I'm getting this error when returning a large number from apollo server
```
      "message": "Int cannot represent non 32-bit signed integer value: 2303492096",
```

Initially I thought it's an issue with GraphQL, but seems that it's actually related an implementation level thing. 
https://github.com/facebook/graphql/issues/73

**Comment by stubailo** [comment]
It's a graphql-js thing - both apollo server and graphql tools are based on graphql-js, Facebook's reference implementation.
