### ISSUE TITLE
GraphQL requests never reach the server for TestFlight/App Store React native app.

### ISSUE THREAD

**Issue by saeho** [apollostack/apollo-server#147]
Since ApolloServer 0.2.x (previously I was using 0.1.x with apolloServer(), now I'm using apolloExpress()) all GraphQL requests made from the React Native app doesn't reach the server. However in Simulator, the requests work and everything is OK with same code.

My server code looks like this with 0.2.x

```
const PORT = 4000;
const executableSchema = makeExecutableSchema({
  typeDefs: Schema,
  resolvers: Resolvers,
});

app.use(passport.initialize());
app.use(passport.session());

app.use( '/graphql', bodyParser.json(), apolloExpress( (req, res, next) => {
  ...
}));
```

Again, everything works fine in SIMULATOR, in AppStore/TestFlight, it does not work.

**Comment by helfer** [comment]
This almost certainly isn't a bug in apollo server. It's probably because you're not configuring something right.
