### ISSUE TITLE
Hapi GrahiQL initial graphql request error

### ISSUE THREAD

**Issue by chasevida** [apollostack/apollo-server#158]
When loading up `GraphiQL` with Hapi there seems to be an initial 400 Bad Request error when calling `/graphql` for introspection purposes. As a result no documentation and code introspection is available. It still does perform general queries correctly as the `/graphql` endpoint seems fine.

Being pretty new to GraphQL and GraphiQL I'm unable to determine if it's something I've done or the way Hapi interfaces with GraphiQL. So I set up examples based on the **Apollo Server** docs and the tests here in this repo. I seem to be able to run everything fine on Express, Connect and Koa - but not Hapi.

The repo where I have setup those servers and the Hapi example is - [https://github.com/chasevida/apollo-server-kits](https://github.com/chasevida/apollo-server-kits). You can see the setup in the file [server.hapi.js](https://github.com/chasevida/apollo-server-kits/blob/master/server.hapi.js).

**Reproduce Issue:**
I've setup a basic example using Apollo Server and Hapi in order to demonstrate the issue.

1. Clone [https://github.com/chasevida/apollo-server-kits](https://github.com/chasevida/apollo-server-kits)
2. `git checkout 4482e57` *(the latest commits implement the suggested workaround)*
3. `npm install`
4. `npm run server:hapi`
5. Browse to `http://localhost:8080/graphiql`
6. You should see the error on screen and in the network console.

**Comment by helfer** [comment]
@nnance I was able to reproduce the issue, but I'm not familiar enough with Hapi to know what's going on. Could you take a quick look? Maybe it's a trivial issue.

**Comment by anibalsolon** [comment]
The main problem is originated from the deep copy of plugin options by Hapi.

Since it accepts a function as argument (in https://github.com/apollostack/apollo-server/blob/master/src/integrations/hapiApollo.ts#L15 ), a workaround is:

```javascript
apolloOptions: () => ({
  schema: executableSchema,
  context: {},
}),
```
because Hapi just copy the function, and not its result/content (obviosly).

**Comment by chasevida** [comment]
Thanks @anibalsolon, I've just tried this out with a few instances of Hapi and Apollo Server and can confirm it works. I've updated my link/repo to reflect the suggested workaround. Cheers.

**Comment by chasevida** [comment]
Thank you @nnance and @anibalsolon - much appreciated.
