### ISSUE TITLE
Query string within formatErrorr's error?

### ISSUE THREAD

**Issue by reggi** [apollostack/apollo-server#161]
Can the query string for a request be added as a property of error? or perhaps as the second argument to the `formatErrorr` callback? I'm trying to create a logging system and I have the error message but not the initial query that caused it. Thoughts?

**Comment by stubailo** [comment]
You could use the query string to generate a new formatError function for each request right?

**Comment by reggi** [comment]
@stubailo Not sure if I understand the question see the commented teeth below 😄 

```javascript
app.use('/graphql', bodyParser.json(), apolloExpress({
  schema: mySchema,
  formatResponse: function (response, {query}) {
    log({query, response}).then()
    return response
  },
  formatError: function (error) {
    // \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
    // Need access to the query here!
    // \/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
    log({error: error.message}).then()
    return error
  }
}))
```

**Comment by helfer** [comment]
@reggi I believe you can get the query from the error itself. Specifically, it's the `source` property of GraphQLError. See here: https://github.com/graphql/graphql-js/blob/master/src/error/GraphQLError.js

**Comment by reggi** [comment]
@helfer Hmmm, that would work, unfortunately I'm throwing normal errors not GraphQLErrors.

**Comment by helfer** [comment]
@reggi I'm pretty sure your normal errors get converted to GraphQLErrors by graphql-js. The original error can then be found on the `originalError` property of GraphQLErrror.

**Comment by reggi** [comment]
`error.source` totally works! Thanks @helfer!!
