### ISSUE TITLE
Looking for a new name!

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo-server#163]
Apollo Server is growing up, and we're looking for a new name that stands on its own. Ideas so far:

- graphql-server
- Pioneer
- Neptune

Ideas are most welcome. We'll probably pick a new name soon, so don't wait until you have the perfect name, just let us know your ideas. Extra points if the package name is still available on npm.

**Comment by TimMikeladze** [comment]
Artemis. Apollo's sister in Greek mythology.

**Comment by stubailo** [comment]
Ooh that's neat!

**Comment by helfer** [comment]
How about this: We call the project Artemis (or Pioneer), convert it to a monorepo, and publish them on npm as: artemis-express, artemis-hapi, artemis-koa, artemis-connect.

Alternatively, we can keep it on the down-low and just call it graphql-server, with the packages being graphql-server-express, graphql-server-hapi, graphql-server-koa, graphql-server-connect.

Thoughts?

**Comment by DxCx** [comment]
If you mean to rename just apollo-server so they will come as a twins (apollo & artemis) then i think its pretty cool. Anyway i think that grpahql-server-* is pretty lame..

**Comment by migueloller** [comment]
I personally like graphql-server because it will be easier for new GraphQL developers to find and be comfortable using.

**Comment by nnance** [comment]
@helfer I like the idea of a monorepo and publishing on npm as artemis-express, etc

**Comment by stubailo** [comment]
@nnance I'm a bit concerned that with names like `artemis-express`, `artemis-hapi`, etc, it will be hard to find them. But that could be solved with marketing as well.

BTW, where does this leave `graphql-tools`? Should we put that under a similar name? Or perhaps just leave it. Curious what @theadactyl thinks about this as well.

**Comment by TimMikeladze** [comment]
I echo the sentiments about having non descriptive names, "graphql" is much more descriptive..

**Comment by helfer** [comment]
@stubailo graphql-tools can just stay graphql-tools, I see no need to change the name there.

**Comment by theadactyl** [comment]
@stubailo I prefer descriptive names here (e.g. graphql-server) for discoverability and legibility. Also think having another "branded" name could cause some confusion; if we do go that way, planetary > greek mythology imo.

**Comment by helfer** [comment]
Maybe a consensus could look as follows:

**Repo name:**
- graphql-server

**Package names:**
- graphql-server-express
- graphql-server-hapi
- graphql-server-koa
- graphql-server-connect

- graphql-server-core
- graphql-server-module-<graphiql, opstore, ...>

How do people feel about these names?

**Comment by gadicc** [comment]
Am I the only one who liked the name Apollo Server?  :)  I quite liked the fact that I got a branded full-stack solution for GraphQL, guaranteed to work well together with feature parity.  So apollostack is just the client-side stack?  But yeah aside from all that I like `graphql-server` best.

Also, personal opinion is it's a pain to have so many packages, both for the dev and for the user (especially with keeping versions in sync).  Do the backend connectors have dependencies on those packages or are they just functions?  I'd much prefer to install one package and then `import apolloExpress from 'graphql-server/lib/express'` or whatever.

**Comment by stubailo** [comment]
This is explicitly part of un-branding it as a "stack" because people often get confused that the parts only work together but not with other GraphQL tools. As you can see with the docs we changed the domain to apollodata.

**Comment by jperl** [comment]
I like `graphql-*` to build off the graphql brand.

**Comment by DxCx** [comment]
so @helfer are we proceeding with graphql-server-* codename?

**Comment by stubailo** [comment]
yes, let's follow @helfer's outline.

**Comment by DxCx** [comment]
Great, then i'll update the monorepo branch for this name :dancer:

**Comment by DxCx** [comment]
thinking of it,
how would you like to rename functions?
for example, apolloExpress?

**Comment by DxCx** [comment]
renaming is ready, just need an answer on the functions themselves

**Comment by stubailo** [comment]
I think leaving the names as-is should be fine.

**Comment by joelgriffith** [comment]
Hate to have many too cooks in the kitchen, but when I was looking for a way to use `habpi` as a graphql instance the apollo server stuff _never_ came up in searches, so I think `graphql-server` is probably a good one as long as FaceBook doesn't have a tight fist around that.

Just my 2 cents

**Comment by stubailo** [comment]
Yep, that's what we are going for. BTW, any discussion about this should go in #164 because having two threads isn't great.

**Comment by DxCx** [comment]
as far as i understand name is chosen, therefore i think we can close this issue...

**Comment by helfer** [comment]
Okay, graphql-server it is!
