### ISSUE TITLE
Loading query for ever when there are syntax errors

### ISSUE THREAD

**Issue by nicolaslopezj** [apollostack/apollo-server#171]
I've noticed that each time I run a query with a error it stays loading for a lot of time and then it responds:

```
TypeError: Failed to fetch
    at TypeError (native)
```

In the server it logs 

```
(STDERR) GraphQL Error: Cannot query field "dme" on type "Query". Did you mean "me"?
(STDERR) GraphQL Error: Cannot read property '0' of undefined
```

I think we are missing a ```try/catch``` in the server.

I'm using Apollo with Meteor.

Is anyone else having this error?

**Comment by helfer** [comment]
@nicolaslopezj I'd be surprised if this was actually happening and we hadn't caught it yet, but it's certainly possible. Could you try and make a PR with a failing test? Thanks!

**Comment by nicolaslopezj** [comment]
I did the test and it passed, took another look into my code and realized that I was having an error in the ```formatError``` function.

```js
console.error(`GraphQL Error: ${error.message}`)
console.error(`At ${error.path[0]}`)
```

With no path, it was giving the error:

```js
(STDERR) GraphQL Error: Cannot read property '0' of undefined
```

We should wrap ```formatError``` in ```try/catch``` to avoid this for other people.
