### ISSUE TITLE
Error properties not available within formatError

### ISSUE THREAD

**Issue by reggi** [apollostack/apollo-server#178]
```js
import ExtendableError from 'es6-error'

export default class MyError extends ExtendableError {
  constructor(args) {
    let code = Object.keys(args)[0]
    let message = Object.values(args)[0]
    super(message)
    this.code = code
  }
}
```

I have a simple error handler works something like this:

```js
let INVALIDREQUEST = 'invalid request'
let e = new MyError({INVALIDREQUEST})
console.log(e.code) // => "INVALIDREQUEST"
```

I'm having trouble because when I log `error.code` from within `formatError` it's not available.

```js
formatError: function (error) {
  console.log(error.code) // => undefined
  return error
}
```

How can I propagate custom properties (like `code`) of `error` from within `formatError`?

> Also posted to [stackoverflow](http://stackoverflow.com/questions/40124494/custom-error-object-with-apollo-server)

**Comment by stubailo** [comment]
Answering this on SO.

**Comment by stubailo** [comment]
http://stackoverflow.com/a/40125568/3280944
