### ISSUE TITLE
GraphQL 0.6.0 compatibility

### ISSUE THREAD

**Issue by syrusakbary** [apollostack/apollo-server#20]
Hey,

I've been using Apollo server for mocking the [Graphene GraphQL schema](http://github.com/graphql-python/graphene) in frontend (js).

I'm using `@include` and `@skip` directives for querying, which seemed were not added into the `buildASTSchema` [until 0.6](https://github.com/graphql/graphql-js/releases/tag/v0.6.0), so `apollo-server` doesn't recognize when you use it when querying.

For fixing this you can mimic what `express-graphql` is doing in it's peer dependencies and update the `graphql` version in `package.json` to `0.6.0`

https://github.com/graphql/express-graphql/blob/master/package.json#L99

**Comment by helfer** [comment]
Thanks, I think #21 will be what you need. Are you using apollo-server or graphql-tools? I recently split the two.

**Comment by helfer** [comment]
New version 0.1.3 published.

**Comment by syrusakbary** [comment]
@helfer using apollo-server. Thanks for the new version! ;)
