### ISSUE TITLE
connector[connectorName] is not a function

### ISSUE THREAD

**Issue by lacker** [apollostack/apollo-server#22]
I'm getting a weird error in initial apollo server setup which seems to be swallowed by the GraphQL layer and it is frustrating because I don't see how I can track it down. I thought all I was doing was roughly copying the example while renaming things, but I must have miscopied something somewhere.

`{
  "data": {
    "getUsers": null
  },
  "errors": [
    {
      "message": "connectors[connectorName] is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}`

Line 2, column 3 of what? It is definitely not within my own code. That error is not too helpful. What should I be doing to track this down?

**Comment by helfer** [comment]
@lacker Yeah, GraphQL error messages aren't easy to debug. The line and column numbers actually correspond to the query. So whatever field is on the second line of your query has a resolve function which throws that error. From the looks of it the error is from some code that tries to initialize connectors. Are you passing any connectors to Apollo Server, and are they constructors? If not, that might be the problem. If that doesn't help you solve it, you can pass the following function as the `formatError` argument to Apollo Server (or a variation thereof which gives you a stack trace or whatever other information you need about the error):

```
function printError(err){
  if(err.originalError){
    console.log(err.originalError);
  } else {
    console.log(err);
  }
  return err;
}
```

PS: We have a PR that should improve error messages in GraphQL. We hope it will make it into GraphQL-JS soon.

**Comment by lacker** [comment]
Mmmm ok I found it. Yeah I really just want the stack trace when something goes wrong, at least when I am running in development mode. That is e.g. how Rails does it. Even if it's just printed out by the server.

**Comment by helfer** [comment]
Agreed. We should make this the default behavior for Apollo Server when no `formatError` function is provided.

**Comment by wzalazar** [comment]
Hi, I have the same error, could you explain how to fix them?

**Comment by stubailo** [comment]
BTW there's an error open for the stack trace thing if anyone wants to look at it: https://github.com/apollostack/apollo-server/issues/111

**Comment by wzalazar** [comment]
Thank's you.

I'm new in Apollo, so I try apollo server in Meteor application and my configuration was 

```
const executableSchema = makeExecutableSchema({
  typeDefs: Schema,
  resolvers: Resolvers,
  connectors: Connectors,
});
```

like show the documentation, and I think the connector was my Meteor collection, My assumption was wrong.
I remove connectors of my configuration and It's works.

Now looks this way 

```
const executableSchema = makeExecutableSchema({
  typeDefs: Schema,
  resolvers: Resolvers,
});
```

**Comment by helfer** [comment]
@wzalazar for connectors, are you passing in an object with string keys, eg. `{ 'collection': collection }`. That's the intended usage.
