### ISSUE TITLE
Benefits over express-graphql

### ISSUE THREAD

**Issue by gonsfx** [apollostack/apollo-server#29]
Why would one want to use this module instead of `express-graphql`?
On a first look it seems it's basically the same.

**Comment by helfer** [comment]
Apollo server and express-graphql do almost the same thing. Apollo server just provides a superset of functionality compared to `express-graphql`. For instance, it lets you easily define your schema in GraphQL schema language. See the docs for more details: http://docs.apollostack.com/apollo-server/tools.html

We're currently refactoring the core to provide integrations with HAPI, express, connect and Koa. Once we're done with that, apollo server will no longer rely on express-graphql internally, and provide extra functionality, like websocket transports, stored queries, query batching etc.

**Comment by gonsfx** [comment]
That sounds interesting, i will keep an eye out. My major pain points with `express-graphql` and `graphql-js` at the moment are fine grained validation of user input and authentication using graphql route.

Thanks for answerin!g :-)

**Comment by denneulin** [comment]
Hi @helfer, do you have any idea of the release date for the your HAPI version ?

**Comment by helfer** [comment]
@denneulin The refactored express version is almost ready and will be merged into master early next week. @nnance has been working on a HAPI implementation alongside that. It's not quite ready yet, but I think it will be soon, because I can start working on it as well next week.

**Comment by helfer** [comment]
Closing this to reduce since I think the original question is basically answered.

**Comment by kfiroo** [comment]
Also in the docs now for anyone wondering https://github.com/apollographql/apollo-server#comparison-with-express-graphql

**Comment by adamchenwei** [comment]
@kfiroo the doc no longer available. reason?

**Comment by johannespfeiffer** [comment]
Git never forgets 😄 
https://github.com/apollographql/apollo-server/tree/cfb086227e623ba1531bb887c3919e224682ccbc#comparison-with-express-graphql
