### ISSUE TITLE
Feature request: Providing an array of resolvers

### ISSUE THREAD

**Issue by ciwolsey** [apollostack/apollo-server#3]
It would be really great if we could provide an array of resolvers and have them merged. Found myself in a scenario where I wanted to load the regular resolvers, but if the server was started with a certain flag it would load another set of resolvers which would override parts of the regular ones.

Specifically it would be great on the server to be able to provide an array of resolvers like so:
```
resolvers: [regularResolvers, sandboxResolvers]
```
In my case I needed sandboxResolvers to overwrite any resolvers with the same name in regularResolvers if a certain flag was set at server startup.

I tried with Object.assign but it didn't work in some situations. I'm doing it with deepmerge NPM for now. Would really appreciate any advice on how to do this in the best way until it's actually implemented as I'm out of my depth somewhat.

**Comment by helfer** [comment]
@ciwolsey I think deepmerge is fine for what you want to do, and that's the way I'd recommend. However, what you're doing sounds pretty similar to [mocking](https://medium.com/apollo-stack/mocking-your-server-with-just-one-line-of-code-692feda6e9cd), so maybe that's something you could look into as an alternative?

**Comment by ciwolsey** [comment]
Now I have a better understanding of how mocks work I'm finding it a suitable solution. The concept of merging resolvers might be useful for other things though and for anyone wanting to do that I can recommend just deep merging them. Perhaps this could be mentioned in the docs if you don't think it's common sense? This can be closed if you like. If you'd like it added to the docs just let me know and I'll put in a PR.

**Comment by helfer** [comment]
@ciwolsey Yeah, I think adding it to the docs would be great! You can add a couple lines here: http://docs.apollostack.com/apollo-server/resolvers.html
