### ISSUE TITLE
Making context available in schema parts resolvers

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/apollo-server#37]
Hi, currently the context is not available when resolving parts of the schema.
This is sometimes needed. Actually in my case quite often, but maybe I'm doing something wrong.

Example:

```
type Schedule {
    _id: String
    name: String
    achievements: [Achievement]
  }

type Achievement {
 ...
}
```

In this case, when I resolve schedules achievements I want to resolve them for the currently logged in user. That is, I need userId to obtain achievements for the given schedule, this ID is available in the context.

Is this actually the place to do this? If not, what would be your recommendation?

**Comment by stubailo** [comment]
Yeah the context is passed to every resolver as the third argument - are you able to access it from there?

**Comment by tomitrescak** [comment]
@stubailo ... not resolvers of queries, but resolvers of types. There I could not access it.

**Comment by helfer** [comment]
@tomitrescak What do you mean with resolvers of types? Only fields have resolvers.

**Comment by tomitrescak** [comment]
Explained by @stubailo ... the problem was that I was testing everything in the GraphiQL environment and it is not picking up the `req.headers.authorization` header, this not initialising the context. I asked the question about it on Slack as well. I can confirm that all resolvers have context as their third parameter.
