### ISSUE TITLE
Options parameter for max query size

### ISSUE THREAD

**Issue by TimMikeladze** [apollostack/apollo-server#40]
In the GitHunt code for the apolloServer config, there is an if statement to throw an error if the query is too long. https://github.com/apollostack/GitHunt/blob/master/api/index.js#L62

Are there benefits to making this check automatic using a default or user provided value in options?

**Comment by helfer** [comment]
That check is rather rudimentary. We're thinking about building some DOS protection into Apollo Server, like rate-limiting, query whitelisting and timeouts. We might also write a validation rule that lets you limit the query cost (determined using schema directives), but limiting the text length of the query is probably not something we'll make a standard option.

**Comment by TimMikeladze** [comment]
That makes a lot more sense! Thanks.

**Comment by stubailo** [comment]
Can't wait to use this!

**Comment by lednhatkhanh** [comment]
Hello, what is the status of those features? @TimMikeladze I couldn't find it anywhere in the docs
