### ISSUE TITLE
Cannot create a enum value with "/" forward slash in schema

### ISSUE THREAD

**Issue by ashah888** [apollostack/apollo-server#52]
I cannot create a enum schema with forward slash ("/").

i.e. the following does not work:
```
  enum Test {
    ABC
    Dog
    Dog/Cat
  }
```

**Comment by helfer** [comment]
Apollo-server uses graphql-tools, which in turn uses graphql-js to parse the schema, so you should file the issue there, if you think this is a bug in the implementation.
