### ISSUE TITLE
Error with `typings.json` when behind a firewall

### ISSUE THREAD

**Issue by juanpaco** [apollostack/apollo-server#55]
I'm trying to install `apollo-server` in my project, but the installation happens in a corporate network that won't let me see type typings repository.  The output that I get:

```
typings ERR! message Unable to connect to "https://api.typings.org/entries/npm/chai/tags/3.5.0%2B20160415060238"
typings ERR! caused by getaddrinfo ENOTFOUND api.typings.org api.typings.org:443
```

I haven't the foggiest how to fix this one, and the answer may be that I'm out of luck because of the weirdness of our networking stuff, but I figured I'd report it anyway.  This one seems *somewhat* related to #54 in that the typings stuff is run post-install.

**Comment by nnance** [comment]
@juanpaco  We made a mistake and released an RC version of the project to NPM.  We have fixed the problem and now when you `npm install apollo-server` you will get version 0.1.5 which is the working version.  Please make sure you use this version until we get the release candidate fully working and documented.

Sorry for any hassle this may have caused.

**Comment by helfer** [comment]
I believe this is fixed now. Feel free to re-open if it's still not working for you.
