### ISSUE TITLE
Install fails at postinstall script 'typings install && npm dedupe'.

### ISSUE THREAD

**Issue by savovs** [apollostack/apollo-server#56]
Hi there, jus tried to install through npm and this happened:

I had  to install typings to fix it.
```
> apollo-server@0.2.0-rc.1 postinstall /Users/Empyreal/WebProjects/knex-2/node_modules/apollo-server
> typings install && npm dedupe

sh: typings: command not found
npm WARN enoent ENOENT: no such file or directory, open '/Users/Empyreal/WebProjects/knex-2/node_modules/db/package.json'
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint@^2.9.0 but none was installed.
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-jsx-a11y@^1.2.0 but none was installed.
npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint@^2.9.0 but none was installed.
npm WARN knex-2@1.0.0 No repository field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-S" "apollo-server"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! apollo-server@0.2.0-rc.1 postinstall: `typings install && npm dedupe`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the apollo-server@0.2.0-rc.1 postinstall script 'typings install && npm dedupe'.

```

**Comment by HriBB** [comment]
Running 
```
npm install --save-dev typings
```
before installing 0.2.0-rc.1 fixed this problem for me.

**Comment by nnance** [comment]
We made a mistake and released an RC version of the project to NPM.  We have fixed the problem and now when you `npm install apollo-server` you will get version 0.1.5 which is the working version.  Please make sure you use this version until we get the release candidate fully working and documented.

Sorry for any hassle this may have caused.

**Comment by helfer** [comment]
I believe this is fixed now. Feel free to re-open if it's still not working for you.

**Comment by savovs** [comment]
I have to say that I'm super happy with apollo. I got my first proper GraphQL server working exactly like I wanted just last night. Thanks for making this awesome project!
