### ISSUE TITLE
File uploads

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo-server#61]
Is there any interest in having apollo server support file uploads like express-graphql does? I'm not sure if file uploads should really go through graphql, but if it's a feature many people want to use, we might consider implementing it.

**Comment by HriBB** [comment]
I am very interested in both apollo server and client supporting file uploads. I was a bit surprised when I found out that there is literally no documentation or examples out there.

+1 from me, unless someone is able to convince me otherwise ;)

**Comment by helfer** [comment]
@HriBB Feel free to give it a try with a PR for the server side!

**Comment by HriBB** [comment]
@helfer and anyone else interested in this ... before I start hacking away, I just want to make sure I am going into the right direction.

I believe that this should be implemented in each integration separately, unless we can use the same `multipart/form-data` parser on all of them? What do you think?

So for `apolloKoa` for example, I would add a check for `multipart/form-data` before the `ctx.request.body` check [here](https://github.com/apollostack/apollo-server/blob/master/src/integrations/koaApollo.ts#L39). If it is indeed `multipart/form-data` request, then store uploaded files into `tmp` folder (or use streams?), read other params (`query`, `operationName`, `variables`) from request and pass everything to `runQuery`. 

Not really sure how to pass uploaded files to the resolvers. Through `variables` or maybe `context`? I am still not 100% sure I understand context completely ... 

Anyway, this is the plan. What do you think? Please let me know if I am on the right track or not.

**Comment by helfer** [comment]
I wrote some comments in your PR. I think the best way would be to first make a PR with a clean failing test (inspired by the one from express-graphql). After that we can make separate PRs with implementations in Express, HAPI and Koa.
