### ISSUE TITLE
Multiple types per field in schema?

### ISSUE THREAD

**Issue by savovs** [apollostack/apollo-server#71]
Hello guys, I'm making a live music app that shows you who's playing, where and when. I want to enable a field to have two possible types.

There are two types of users that can post "events". Is this type thing possible? If yes, how would you make it work? I have an owner_type column in my database that can be 'artist' or 'venue', but I don't know how I can use it to set the type in Apollo. 

```graphql
type Event {
	owner: Artist || Venue,  // I want to set the type based on a value read from the DB using knex
	venue: Venue,
	artists: [Artist],
}

type Artist {
	events: [Event],
}

type Venue {
	events: [Event],
}
```

Currently I'm working around this by setting it like this: 

```
type Event {
	owner_id: Int,
    owner_type: String,
	venue: Venue,
	artists: [Artist],
}
```

**Comment by helfer** [comment]
You can use a union: 
```
union ArtistOrVenue = Artist | Venue
```

**Comment by savovs** [comment]
Thanks @helfer, I can't seem to find info in the docs about how to resolve the union. How do I control which type is selected?

**Comment by townmulti** [comment]
In you Resolvers section, what does `info.schema.getType('Artist')` return?

```
    Owner: { // this needs to receive an object with a type property for it to work, check your connectors!
        __resolveType(owner, ctx, info) {
            if(owner.type == 'artist') {
                return info.schema.getType('Artist');
            } else return info.schema.getType('Venue');
        },
    }
```

I'm trying to figure out exactly what I should be returning here. I have a type field on my unioned objects.

**Comment by DxCx** [comment]
Hi @twonmulti

It will return the GraphQLObjectType defined for them.
Then this is what resolveType will return to resolve the abstract type..
