### ISSUE TITLE
apolloOptions.context type and default value

### ISSUE THREAD

**Issue by lvauvillier** [apollostack/apollo-server#75]
By default context is undefined and has a type to `any`.

`attachConnectorsToContext` from `graphql-tools` works only with an `object` typed context.
If context is undefined, it will raise an error for each requests. 

So, we have to explicitely set context to an empty object to make it working :

```
server.use('/', bodyParser.json(), apolloExpress({
  schema: executableSchema,
  context: {},
}));
```

Maybe apolloOptions.context can have a default value setted to `{}` and be explicitely typed as `Object`.

**Comment by helfer** [comment]
Yeah, it's true that there's a bit of a mismatch. The reason we let it be `any` is that graphql-js accepts `any` as the context, and we don't want to change that function signature with apollo server. Maybe there's a place in the documentation where we can make it clear that if connectors are used, the context has to be explicitly set to an empty object first?

**Comment by vedmalex** [comment]
@helfer it will be very helpfull, i've moving to new server and spent some time to make it works, before i found the solution!

**Comment by helfer** [comment]
If someone could submit a PR to the docs, that would be great! 😃

**Comment by tomitrescak** [comment]
Guys, since context now it an object, how can I modify context based on request? In Meteor the context is filled with userID, so how can this be achieved with the new design ?

I need context to be a function that accepts request.

**Comment by helfer** [comment]
I think this issue is mostly solved, so I'll close this. Feel free to open again if there's still something to discuss.
