### ISSUE TITLE
GraphiQL endpoint broken after migrating to 0.2? "Apollo Server supports only POST requests"

### ISSUE THREAD

**Issue by sebastienbarre** [apollostack/apollo-server#76]
Hi guys. Thanks for the great work!
My small Apollo server example was working fine at 0.1, but after following the [exact migration path to 0.2](http://docs.apollostack.com/apollo-server/migration.html) and double checking against the [Apollo Server GraphiQL docs page](http://docs.apollostack.com/apollo-server/graphiql.html), the server no longer seems to serve GraphiQL correctly.

The page: `localhost:9090/graphql` always returns `Apollo Server supports only POST requests` and the GraphiQL GUI never shows up.
Now it's unclear to me if both can be at the same endpoint, as stated in both examples in the doc:
```
graphQLServer.use('/graphql', bodyParser.json(), apolloExpress({
  schema: executableSchema,
}));
graphQLServer.use('/graphiql', graphiqlExpress({
  endpointURL: '/graphql',
}));
```
but changing the GraphiQL endpoint to '/graphiql' will bring the UI back, but executing any GraphQL example there will still fail.
Thanks

**Comment by helfer** [comment]
What error message do you get when executing a query from `/graphiql`? Does the network tab show that a request to `/graphql` is made from the GraphiQL UI?

**Comment by sebastienbarre** [comment]
This looks like a user error on my side, my apologies. I must have tried the `/graphql` endpoint first, be confused by the message, modified the code, then tried the `/graphiql`, which I had broken already by changing the `endpointURL`. Closing (feel free to nuke the issue entirely).
