### ISSUE TITLE
__parseLiteral (custom validation) not called when using mutation variables

### ISSUE THREAD

**Issue by richardkall** [apollostack/apollo-server#82]
Hi!

I've added a custom scalar for email, with validation method inside the `__parseLiteral` function. However, when I use variables, `__parseLiteral` is not being called and it skips my validation. The value is returned immediately.

### This works, runs email validation:

```
mutation {
  createUser(email: "test@example.com", password: "password") {
    user {
      id
      email
    }
  }
}
```

### This does not work, skips email validation:

```
mutation($email: Email!, $password: Password!) {
  createUser(email: $email, password: $password) {
    user {
      id
      email
    }
  }
}
```

Variables sent:

```
{
  "email": "test@example.com",
  "password": "password"
}
```

### Email scalar type

```
import {GraphQLError} from 'graphql/error';

import {isEmail} from '../../../utils/validations';

export default {
  __parseValue: (value) => value.toLowerCase(),
  __serialize: (value) => value.toLowerCase(),
  __parseLiteral: ({value}) => {
    if (!isEmail(value)) {
      throw new GraphQLError('Email is not valid.');
    }

    return value.toLowerCase();
  }
};
```

Really appreciate if you could look into this, thank you. Let me know if you need any more details.

**Comment by helfer** [comment]
Hi @richardkall, could you do me a favor and verify that the behavior is different if you use just graphql-js on its own? If I remember correctly, graphql-js doesn't use parseLiteral on variables, because variables are already parsed as JSON. If you want to do validation, I think your only choice is to do so inside the resolve functions.

**Comment by sammkj** [comment]
@helfer , I copied and pasted the `Date` example from apollo docs and it didn't work. As stated above, `__parseLiteral` is not being called.

**Comment by helfer** [comment]
@sammkj: As I stated above, I think that's how graphql-js works.

See also:
https://github.com/graphql/graphql-js/issues/187

**Comment by sammkj** [comment]
Ah I see. Thanks for the reference!

**Comment by richardkall** [comment]
Thanks for replying and sorry for not checking this in graphql-js first.

I ended up moving the validation to the User model (Mongoose) and throwing any validation errors in the resolve function for the mutation. I could then also remove my custom Email scalar and just use the String scalar. Less files! :)

**Comment by stubailo** [comment]
@richardkall can't you use `_parseValue` for this? That's the equivalent of `_parseLiteral` for variables..
