### ISSUE TITLE
Koa: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by voodooattack** [apollostack/apollo-server#84]
When I use apolloKoa with koa-router like this:
```
const app = koa();
const router = new Router();
const apolloMiddleware = apolloKoa({ schema });

app.use(koaBody());

router.post('/api', apolloMiddleware);

app.use(router.routes());
app.use(router.allowedMethods());
```
I get the following error:
```
  TypeError: Cannot read property 'body' of undefined
      at /home/voodooattack/dev/foxls/node_modules/apollo-server/dist/integrations/koaApollo.js:35:25
      at undefined.next (native)
      at fulfilled (/home/voodooattack/dev/foxls/node_modules/apollo-server/dist/integrations/koaApollo.js:4:58)
      at run (/home/voodooattack/dev/foxls/node_modules/core-js/modules/es6.promise.js:87:22)
      at /home/voodooattack/dev/foxls/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (/home/voodooattack/dev/foxls/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

package.json:
```
  "dependencies": {
    "apollo-client": "^0.4.11",
    "apollo-server": "^0.2.3",
  }
```

**Comment by HriBB** [comment]
Which version are you using? Currently we only support v2.

**Comment by voodooattack** [comment]
@HriBB Thank you, I just upgraded to koa 2 and it all works. It would be useful if this was mentioned in the documentation.

**Comment by HriBB** [comment]
@voodooattack great to hear that! But you were lucky to be able to switch to v2 easily, other users might not have that option, if their entire app is already built around v1.

It would be cool if we supported both versions and threw an error if user used the wrong version. The syntax from v1 to v2 changed only slightly, and I suspect that it should be possible to detect version and adjust `apolloKoa()` or simply provide `apolloKoa()` and `apolloKoa2()`.

@helfer what do you think about this? How should we approach this if we decide to support koa v1?

**Comment by helfer** [comment]
@HriBB If you can make it work for both versions, that would be great! Even if the export is different, that's fine as long as the code is mostly shared. I'd say go for it!

**Comment by cvburgess** [comment]
will the koa-convert utility help with this?
