### ISSUE TITLE
Proposal: Restify support

### ISSUE THREAD

**Issue by rricard** [apollostack/apollo-server#85]
[Restify](http://restify.com/) has been a popular option to create API servers a while back. As of today, at [Jolicloud](https://home.desktop.pro/), we're using restify since it was decided a while back it was the right tool for the job. It is now wildly used in our codebase and we can't really detach ourselves from it.

Currently, we managed to get [express-graphql](https://github.com/graphql/express-graphql) work in it, even in production, but we'd like to have a really supported implementation with Apollo Server.

Since v0.2 was released, I was wondering if you planned to integrate it or if I could contribute by adding it as well.

Thank you!

**Comment by helfer** [comment]
@rricard Yes, I'm definitely for adding support for Restify! But at the moment I'm having a bit of trouble seeing how you would integrate it tightly with Apollo Server? Would you just use it as an alternative to Express, HAPI, Koa, etc?

Is the idea to essentially use Restify as a backend and automatically generate resolvers or a schema somehow?

If you have an example for how you integrated express-graphql in Restify and what you would like the integration to look like in an ideal world, that would be great!

**Comment by rricard** [comment]
The main issue with restify is it can't live with express in the same codebase since both override stuff globally. We need our graphql schema in the same codebase ...

Right now it looks like that:

```js
const graphqlHTTP = require('express-graphql');

const graphQLEndpoint = graphqlHTTP(...);

app.get('/graphql', graphQLEndpoint);
app.post('/graphql', graphQLEndpoint);
```

It works but I think we could do better!

**Comment by rricard** [comment]
For instance we could define the graphql endpoint as a middleware. I'll try to think of a correct API and propose that to you!

**Comment by stubailo** [comment]
@rricard can't you use Apollo Server the same way? http://docs.apollostack.com/apollo-server/setup.html#apolloExpress

**Comment by rricard** [comment]
Last time I checked, it failed with internals. At least if we want to go that way and use restify via the express support, tests should be added to ensure restify is not broken. I should start with that...

**Comment by helfer** [comment]
@rricard Yeah, that's a great idea. If you add tests, that will also be a great way to point to concrete examples for how to use it.

**Comment by helfer** [comment]
@rricard are you still interested in this? I think it would be pretty useful! Let me know if I can help in any way.

**Comment by rricard** [comment]
@helfer yes, sorry, forgot a bit about it! I have a lot to do currently (mainly client stuff, that's why the PRs are going there... 😉 ) but yes, I still plan doing that at some point!

**Comment by rricard** [comment]
@helfer I've got great news! I finally tried to run apollo-server on restify: it works perfectly 🎉 . So the idea now is to write tests to ensure we don't break compat with restify, I'll work on that myself. I'll also write some docs on how to integrate w/ restify!

**Comment by rricard** [comment]
Closing in favor of #125

**Comment by stubailo** [comment]
Thank for looking into this!
