### ISSUE TITLE
Readme.md missing resolvers

### ISSUE THREAD

**Issue by linonetwo** [apollostack/apollo-server#86]
In [https://github.com/apollostack/apollo-server#options](https://github.com/apollostack/apollo-server#options) it missing resolvers:
```
schema: the GraphQLSchema to be used
context: the context value passed to resolvers during GraphQL execution
rootValue: the value passed to the first resolve function
formatError: a function to apply to every error before sending the response to clients
validationRules: additional GraphQL validation rules to be applied to client-specified queries
formatParams: a function applied for each query in a batch to format parameters before execution
formatResponse: a function applied to each response after execution
```

It actually be like this in the GitHunt example:
```javascript
    graphiql: true,
    pretty: true,
    resolvers,  // 为 Schema 取数据的秘书
    schema,    // 定义数据的大佬
    context: {
      ...
    },
```

seems missing something?

**Comment by helfer** [comment]
@linonetwo We recently updated Apollo Server to Version 0.2, but GitHunt still uses version 0.1.5. We should fix that as soon as possible :)

**Comment by linonetwo** [comment]
OK，so resolvers now is part of schema ? When being delivered into apollo-server

**Comment by linonetwo** [comment]
It's interesting to see makeExecutableSchema hahaha, thanks for this quick updating.
