### ISSUE TITLE
Ditching async

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/apollo-server#93]
Guys, in all your examples you advocate using async with queries on server. Concerning that node 6.x can now run vanilla es2015 it is the only thing that requires transpilation. I tried not to use async call but I was running through poopstorm of problems with fibers and all. What would be a recommended strategy without asyns/await? Would you care to provide functioning example of e.g. a resolver or mutation without async call, for example based on Promises? I tried several startegies and none seems to work.

**Comment by helfer** [comment]
#92 might solve your problems.

**Comment by helfer** [comment]
Is this still an issue? If so, can you provide a clear description of what you're trying to accomplish and what exact errors you run into?
