### ISSUE TITLE
Afterware for express?

### ISSUE THREAD

**Issue by katopz** [apollostack/apollo-server#96]
Hi guys,

I'm try to implement `304` response to `If-None-Match` (by `etag`) from client.
And I need to calculate `etag` from response body around [here](https://github.com/apollostack/apollo-server/blob/master/src/integrations/expressApollo.ts#L107) if I understand it right.

So seem like I need an `afterware` supported there at server side. so the question is 

- Can I expect `afterware` supported there?
- Or do I need to PR for `afterware`?

IMHO `etag` and `last-modified` is a must have (you guy aim for speed right?) so it should implement internally and can be turn on and off like `express` did for static `etag` do tell me if you want me to PR for `304` response internally instead of `afterware` approach.

Thanks

**Comment by helfer** [comment]
@katopz I think it should be possible to do this with normal express middleware, or is that not the case? We do care about performance, but we also care about simplicity. I think implementing this outside of apollo server would cost almost nothing in terms of speed, but it would keep apollo server much simpler.

As a next step, could you figure out what (if anything) we would need to change to support the approach outlined in this stackoverflow answer: http://stackoverflow.com/questions/24542959/how-does-a-etag-work-in-expressjs

**Comment by katopz** [comment]
@helfer Cool thanks. I'll close this for now and will keep you post if the result turnout well :)
