### ISSUE TITLE
graphql along with existing hapijs routes

### ISSUE THREAD

**Issue by BhaskaranR** [apollostack/apollo-server#97]
Hi,
 I currently have some rest services which i don’t want to convert to graphql. For the new services i would like to use GraphQL. 

I tried registering both hapijs rest api routes and graphql. I could still access the rest api but could not access graphql route unless the auth strategy is commented. I need the auth for my existing routes. How do I configure auth for graphql route?

server.auth.strategy('jwt', 'jwt', true,
        { key: config.get("jwtSecret"),
            validateFunc: validate,
            verifyOptions: { ignoreExpiration: true }
        });

server.register({
   register: new apollo.ApolloHAPI(),
   options: graphqlOptions,
   routes: { prefix: '/graphql' },
});

server.register({
   register: new apollo.GraphiQLHAPI(),
   options: { endpointURL: '/graphql' },
});

   server.route(user.routes);
   server.route(device.routes);
   server.route(posts.routes);

**Comment by helfer** [comment]
Can you describe the problem a bit more accurately? Do you not want to authenticate the requests made to the graphql route? If that's your issue, I think it might be a HAPI configuration problem, not an issue with Apollo Server.

**Comment by BhaskaranR** [comment]
Do you not want to authenticate the requests made to the graphql route? no, but the existing rest api routes take in auth, which break the graphql route. I get a 401 for the graphql route. how can i specify config : { auth : false }for graphql route?

{"statusCode":401,"error":"Unauthorized","message":"Missing authentication"}

**Comment by BhaskaranR** [comment]
@helfer any pointer please? do you have any example that uses both rest service and graphql with the auth strategy?

**Comment by BhaskaranR** [comment]
@helfer I have hit a road block with this. Can you please let me know if the apollo server plugin takes the config : { auth : false } or the auth strategy set by hapi server?? I tried setting in the options, routes etc.  nothing works. Am I doing something wrong?

**Comment by helfer** [comment]
@BhaskaranR I don't know, because I didn't write that part. Maybe @nnance can help?

If I were you, I would try send the authentication token with the graphql request as well, because presumably you already have it on the client? Alternatively you can run two separate servers.

PS: I see you already found this issue, so I think you have your answer: https://github.com/hapijs/discuss/issues/162

PPS: It seems this would be easy if we used `server.route` instead of `server.register`. @nnance what's the reason we need to use register vs. route?

**Comment by nnance** [comment]
@BhaskaranR I am working on some improvements to the HAPI implementation and this is one area I am working on improving.  I will reach out when I have more detail

**Comment by SimonDegraeve** [comment]
I see only three ways to allow full control on HAPI routes:

1) Get the route configuration from the plugin constructor.
```js
import { Server } from 'hapi';
import { ApolloHAPI as Apollo } from 'apollo-server';

const server = new Server();
server.connection({ port: 3000 });

server.register({
  register: new Apollo({
    route: {
      // Route configuration
    }
  }),
  options: { schema: myGraphQLSchema },
  routes: { prefix: '/graphql' },
});
```
2) Export a handler creator and let people build their own route if they want to. 
```js
import { Server } from 'hapi';
import { createApolloHandler } from 'apollo-server';

const server = new Server();
server.connection({ port: 3000 });

const apolloHandler = createApolloHandler({ schema: myGraphQLSchema });

server.route({
  method: 'POST',
  path: '/',
  config: {
    handler: apolloHandler,
    // Route configuration
  },
});
```
3) Change the shape of the options passed to the register function. 
```js
import { Server } from 'hapi';
import { ApolloHAPI as Apollo } from 'apollo-server';

const server = new Server();
server.connection({ port: 3000 });

server.register({
  register: new Apollo(),
  options: { 
    route: {
      // Route configuration
    },
    schema: myGraphQLSchema },
  routes: { prefix: '/graphql' },
});
```
The 3) is the closest to the HAPI ecosystem but require a breaking change.

**Comment by helfer** [comment]
@SimonDegraeve @nnance I think we'll bump the version for the next release, so a breaking change won't be an issue. Let's make sure we make the API as close to perfect as we can!

**Comment by nnance** [comment]
@SimonDegraeve @BhaskaranR I have opened a PR that should resolve this issue.  Feedback welcome.  #127
