### ISSUE TITLE
Add support for node 0.10? 

### ISSUE THREAD

**Issue by lorensr** [apollostack/apollo-server#99]
From the below error, looks like we're not doing prepublish transpiling to be compatible with node `0.10` (and meteor `<1.4`). Seems like this process is standard for client-side npm libs, don't know about server-side.

https://github.com/apollostack/meteor-starter-kit/issues/24

**Comment by helfer** [comment]
Yeah, you're right, our compile target is ES6 (because TS doesn't support async for es5). I don't have time for it right now, but if someone could add a PR to add babel to the compilation step, that would be great!

**Comment by helfer** [comment]
Alternatively, would it be an option to make meteor-integration work only with meteor 1.4 and above? To me that doesn't sound too unreasonable.

**Comment by lorensr** [comment]
Yep, the latest version of `meteor/apollo` is 1.4-only. Just a question of whether apollo-server wants to support `node v0.10`. It comes out of LTS in October, so there probably won't be many still on that version

**Comment by helfer** [comment]
Yeah, given that support for it will be dropped soon I don't think it's worth for us to invest time in that. I'll close the issue, but we can reopen it if necessary.
